/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MailUiModule extends AbstractMailUiModule {

	public MailUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
