/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.Mail.ui.internal.MailActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MailExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MailActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MailActivator activator = MailActivator.getInstance();
		return activator != null ? activator.getInjector(MailActivator.ORG_XTEXT_EXAMPLE_MYDSL_MAIL) : null;
	}

}
