/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MailGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Mail.Model");
		private final RuleCall cAlefasoMailakaParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Model:
		//    AlefasoMailaka;
		@Override public ParserRule getRule() { return rule; }
		
		//AlefasoMailaka
		public RuleCall getAlefasoMailakaParserRuleCall() { return cAlefasoMailakaParserRuleCall; }
	}
	public class AlefasoMailakaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Mail.AlefasoMailaka");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAlefasoMailakaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cHafatraKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMessageAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMessageSTRINGTerminalRuleCall_4_0 = (RuleCall)cMessageAssignment_4.eContents().get(0);
		private final Keyword cLohahevitraKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cObjet_de_mailAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cObjet_de_mailSTRINGTerminalRuleCall_7_0 = (RuleCall)cObjet_de_mailAssignment_7.eContents().get(0);
		private final Keyword cAnyaminyKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cColonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cRecipientsAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cRecipientsEmailRecipientParserRuleCall_10_0 = (RuleCall)cRecipientsAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cCommaKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cRecipientsAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cRecipientsEmailRecipientParserRuleCall_11_1_0 = (RuleCall)cRecipientsAssignment_11_1.eContents().get(0);
		private final Keyword cMpandefaKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cColonKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cSenderAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cSenderSTRINGTerminalRuleCall_14_0 = (RuleCall)cSenderAssignment_14.eContents().get(0);
		private final Keyword cTenymiafinaKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cColonKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Assignment cPasswordAssignment_17 = (Assignment)cGroup.eContents().get(17);
		private final RuleCall cPasswordSTRINGTerminalRuleCall_17_0 = (RuleCall)cPasswordAssignment_17.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_18 = (Keyword)cGroup.eContents().get(18);
		
		//AlefasoMailaka:
		//    'AlefasoMailaka' '['
		//        'Hafatra' ':' message=STRING
		//        'Lohahevitra' ':' objet_de_mail=STRING
		//        'Anyaminy' ':' recipients+=EmailRecipient (',' recipients+=EmailRecipient)*
		//        'Mpandefa' ':' sender=STRING
		//        'Tenymiafina' ':' password=STRING
		//    ']';
		@Override public ParserRule getRule() { return rule; }
		
		//'AlefasoMailaka' '['
		//    'Hafatra' ':' message=STRING
		//    'Lohahevitra' ':' objet_de_mail=STRING
		//    'Anyaminy' ':' recipients+=EmailRecipient (',' recipients+=EmailRecipient)*
		//    'Mpandefa' ':' sender=STRING
		//    'Tenymiafina' ':' password=STRING
		//']'
		public Group getGroup() { return cGroup; }
		
		//'AlefasoMailaka'
		public Keyword getAlefasoMailakaKeyword_0() { return cAlefasoMailakaKeyword_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }
		
		//'Hafatra'
		public Keyword getHafatraKeyword_2() { return cHafatraKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//message=STRING
		public Assignment getMessageAssignment_4() { return cMessageAssignment_4; }
		
		//STRING
		public RuleCall getMessageSTRINGTerminalRuleCall_4_0() { return cMessageSTRINGTerminalRuleCall_4_0; }
		
		//'Lohahevitra'
		public Keyword getLohahevitraKeyword_5() { return cLohahevitraKeyword_5; }
		
		//':'
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//objet_de_mail=STRING
		public Assignment getObjet_de_mailAssignment_7() { return cObjet_de_mailAssignment_7; }
		
		//STRING
		public RuleCall getObjet_de_mailSTRINGTerminalRuleCall_7_0() { return cObjet_de_mailSTRINGTerminalRuleCall_7_0; }
		
		//'Anyaminy'
		public Keyword getAnyaminyKeyword_8() { return cAnyaminyKeyword_8; }
		
		//':'
		public Keyword getColonKeyword_9() { return cColonKeyword_9; }
		
		//recipients+=EmailRecipient
		public Assignment getRecipientsAssignment_10() { return cRecipientsAssignment_10; }
		
		//EmailRecipient
		public RuleCall getRecipientsEmailRecipientParserRuleCall_10_0() { return cRecipientsEmailRecipientParserRuleCall_10_0; }
		
		//(',' recipients+=EmailRecipient)*
		public Group getGroup_11() { return cGroup_11; }
		
		//','
		public Keyword getCommaKeyword_11_0() { return cCommaKeyword_11_0; }
		
		//recipients+=EmailRecipient
		public Assignment getRecipientsAssignment_11_1() { return cRecipientsAssignment_11_1; }
		
		//EmailRecipient
		public RuleCall getRecipientsEmailRecipientParserRuleCall_11_1_0() { return cRecipientsEmailRecipientParserRuleCall_11_1_0; }
		
		//'Mpandefa'
		public Keyword getMpandefaKeyword_12() { return cMpandefaKeyword_12; }
		
		//':'
		public Keyword getColonKeyword_13() { return cColonKeyword_13; }
		
		//sender=STRING
		public Assignment getSenderAssignment_14() { return cSenderAssignment_14; }
		
		//STRING
		public RuleCall getSenderSTRINGTerminalRuleCall_14_0() { return cSenderSTRINGTerminalRuleCall_14_0; }
		
		//'Tenymiafina'
		public Keyword getTenymiafinaKeyword_15() { return cTenymiafinaKeyword_15; }
		
		//':'
		public Keyword getColonKeyword_16() { return cColonKeyword_16; }
		
		//password=STRING
		public Assignment getPasswordAssignment_17() { return cPasswordAssignment_17; }
		
		//STRING
		public RuleCall getPasswordSTRINGTerminalRuleCall_17_0() { return cPasswordSTRINGTerminalRuleCall_17_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_18() { return cRightSquareBracketKeyword_18; }
	}
	public class EmailRecipientElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Mail.EmailRecipient");
		private final Assignment cEmailAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cEmailSTRINGTerminalRuleCall_0 = (RuleCall)cEmailAssignment.eContents().get(0);
		
		//EmailRecipient:
		//    email=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//email=STRING
		public Assignment getEmailAssignment() { return cEmailAssignment; }
		
		//STRING
		public RuleCall getEmailSTRINGTerminalRuleCall_0() { return cEmailSTRINGTerminalRuleCall_0; }
	}
	
	
	private final ModelElements pModel;
	private final AlefasoMailakaElements pAlefasoMailaka;
	private final EmailRecipientElements pEmailRecipient;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MailGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pAlefasoMailaka = new AlefasoMailakaElements();
		this.pEmailRecipient = new EmailRecipientElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.Mail".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    AlefasoMailaka;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//AlefasoMailaka:
	//    'AlefasoMailaka' '['
	//        'Hafatra' ':' message=STRING
	//        'Lohahevitra' ':' objet_de_mail=STRING
	//        'Anyaminy' ':' recipients+=EmailRecipient (',' recipients+=EmailRecipient)*
	//        'Mpandefa' ':' sender=STRING
	//        'Tenymiafina' ':' password=STRING
	//    ']';
	public AlefasoMailakaElements getAlefasoMailakaAccess() {
		return pAlefasoMailaka;
	}
	
	public ParserRule getAlefasoMailakaRule() {
		return getAlefasoMailakaAccess().getRule();
	}
	
	//EmailRecipient:
	//    email=STRING;
	public EmailRecipientElements getEmailRecipientAccess() {
		return pEmailRecipient;
	}
	
	public ParserRule getEmailRecipientRule() {
		return getEmailRecipientAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
