/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.Mail.ui.internal.MailActivator;

public class MailUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MailActivator.getInstance().getInjector("org.xtext.example.mydsl.Mail");
	}

}
