/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.mail;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Alefaso Mailaka</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mail.AlefasoMailaka#getMessage <em>Message</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mail.AlefasoMailaka#getObjet_de_mail <em>Objet de mail</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mail.AlefasoMailaka#getRecipients <em>Recipients</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mail.AlefasoMailaka#getSender <em>Sender</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mail.AlefasoMailaka#getPassword <em>Password</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.mail.MailPackage#getAlefasoMailaka()
 * @model
 * @generated
 */
public interface AlefasoMailaka extends Model
{
  /**
   * Returns the value of the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' attribute.
   * @see #setMessage(String)
   * @see org.xtext.example.mydsl.mail.MailPackage#getAlefasoMailaka_Message()
   * @model
   * @generated
   */
  String getMessage();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mail.AlefasoMailaka#getMessage <em>Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message</em>' attribute.
   * @see #getMessage()
   * @generated
   */
  void setMessage(String value);

  /**
   * Returns the value of the '<em><b>Objet de mail</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objet de mail</em>' attribute.
   * @see #setObjet_de_mail(String)
   * @see org.xtext.example.mydsl.mail.MailPackage#getAlefasoMailaka_Objet_de_mail()
   * @model
   * @generated
   */
  String getObjet_de_mail();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mail.AlefasoMailaka#getObjet_de_mail <em>Objet de mail</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objet de mail</em>' attribute.
   * @see #getObjet_de_mail()
   * @generated
   */
  void setObjet_de_mail(String value);

  /**
   * Returns the value of the '<em><b>Recipients</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.mail.EmailRecipient}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Recipients</em>' containment reference list.
   * @see org.xtext.example.mydsl.mail.MailPackage#getAlefasoMailaka_Recipients()
   * @model containment="true"
   * @generated
   */
  EList<EmailRecipient> getRecipients();

  /**
   * Returns the value of the '<em><b>Sender</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sender</em>' attribute.
   * @see #setSender(String)
   * @see org.xtext.example.mydsl.mail.MailPackage#getAlefasoMailaka_Sender()
   * @model
   * @generated
   */
  String getSender();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mail.AlefasoMailaka#getSender <em>Sender</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sender</em>' attribute.
   * @see #getSender()
   * @generated
   */
  void setSender(String value);

  /**
   * Returns the value of the '<em><b>Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Password</em>' attribute.
   * @see #setPassword(String)
   * @see org.xtext.example.mydsl.mail.MailPackage#getAlefasoMailaka_Password()
   * @model
   * @generated
   */
  String getPassword();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mail.AlefasoMailaka#getPassword <em>Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Password</em>' attribute.
   * @see #getPassword()
   * @generated
   */
  void setPassword(String value);

} // AlefasoMailaka
