/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.mail;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Email Recipient</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mail.EmailRecipient#getEmail <em>Email</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.mail.MailPackage#getEmailRecipient()
 * @model
 * @generated
 */
public interface EmailRecipient extends EObject
{
 

/**
   * Returns the value of the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Email</em>' attribute.
   * @see #setEmail(String)
   * @see org.xtext.example.mydsl.mail.MailPackage#getEmailRecipient_Email()
   * @model
   * @generated
   */
  String getEmail();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.mail.EmailRecipient#getEmail <em>Email</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Email</em>' attribute.
   * @see #getEmail()
   * @generated
   */
  void setEmail(String value);

} // EmailRecipient
