/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.mail;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.mail.MailFactory
 * @model kind="package"
 * @generated
 */
public interface MailPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mail";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Mail";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mail";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MailPackage eINSTANCE = org.xtext.example.mydsl.mail.impl.MailPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mail.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mail.impl.ModelImpl
   * @see org.xtext.example.mydsl.mail.impl.MailPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mail.impl.AlefasoMailakaImpl <em>Alefaso Mailaka</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mail.impl.AlefasoMailakaImpl
   * @see org.xtext.example.mydsl.mail.impl.MailPackageImpl#getAlefasoMailaka()
   * @generated
   */
  int ALEFASO_MAILAKA = 1;

  /**
   * The feature id for the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALEFASO_MAILAKA__MESSAGE = MODEL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Objet de mail</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALEFASO_MAILAKA__OBJET_DE_MAIL = MODEL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Recipients</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALEFASO_MAILAKA__RECIPIENTS = MODEL_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Sender</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALEFASO_MAILAKA__SENDER = MODEL_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALEFASO_MAILAKA__PASSWORD = MODEL_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Alefaso Mailaka</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALEFASO_MAILAKA_FEATURE_COUNT = MODEL_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.mail.impl.EmailRecipientImpl <em>Email Recipient</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.mail.impl.EmailRecipientImpl
   * @see org.xtext.example.mydsl.mail.impl.MailPackageImpl#getEmailRecipient()
   * @generated
   */
  int EMAIL_RECIPIENT = 2;

  /**
   * The feature id for the '<em><b>Email</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMAIL_RECIPIENT__EMAIL = 0;

  /**
   * The number of structural features of the '<em>Email Recipient</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EMAIL_RECIPIENT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mail.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.mail.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mail.AlefasoMailaka <em>Alefaso Mailaka</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alefaso Mailaka</em>'.
   * @see org.xtext.example.mydsl.mail.AlefasoMailaka
   * @generated
   */
  EClass getAlefasoMailaka();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mail.AlefasoMailaka#getMessage <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Message</em>'.
   * @see org.xtext.example.mydsl.mail.AlefasoMailaka#getMessage()
   * @see #getAlefasoMailaka()
   * @generated
   */
  EAttribute getAlefasoMailaka_Message();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mail.AlefasoMailaka#getObjet_de_mail <em>Objet de mail</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Objet de mail</em>'.
   * @see org.xtext.example.mydsl.mail.AlefasoMailaka#getObjet_de_mail()
   * @see #getAlefasoMailaka()
   * @generated
   */
  EAttribute getAlefasoMailaka_Objet_de_mail();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.mail.AlefasoMailaka#getRecipients <em>Recipients</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Recipients</em>'.
   * @see org.xtext.example.mydsl.mail.AlefasoMailaka#getRecipients()
   * @see #getAlefasoMailaka()
   * @generated
   */
  EReference getAlefasoMailaka_Recipients();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mail.AlefasoMailaka#getSender <em>Sender</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sender</em>'.
   * @see org.xtext.example.mydsl.mail.AlefasoMailaka#getSender()
   * @see #getAlefasoMailaka()
   * @generated
   */
  EAttribute getAlefasoMailaka_Sender();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mail.AlefasoMailaka#getPassword <em>Password</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Password</em>'.
   * @see org.xtext.example.mydsl.mail.AlefasoMailaka#getPassword()
   * @see #getAlefasoMailaka()
   * @generated
   */
  EAttribute getAlefasoMailaka_Password();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.mail.EmailRecipient <em>Email Recipient</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Email Recipient</em>'.
   * @see org.xtext.example.mydsl.mail.EmailRecipient
   * @generated
   */
  EClass getEmailRecipient();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.mail.EmailRecipient#getEmail <em>Email</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Email</em>'.
   * @see org.xtext.example.mydsl.mail.EmailRecipient#getEmail()
   * @see #getEmailRecipient()
   * @generated
   */
  EAttribute getEmailRecipient_Email();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MailFactory getMailFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mail.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mail.impl.ModelImpl
     * @see org.xtext.example.mydsl.mail.impl.MailPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mail.impl.AlefasoMailakaImpl <em>Alefaso Mailaka</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mail.impl.AlefasoMailakaImpl
     * @see org.xtext.example.mydsl.mail.impl.MailPackageImpl#getAlefasoMailaka()
     * @generated
     */
    EClass ALEFASO_MAILAKA = eINSTANCE.getAlefasoMailaka();

    /**
     * The meta object literal for the '<em><b>Message</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALEFASO_MAILAKA__MESSAGE = eINSTANCE.getAlefasoMailaka_Message();

    /**
     * The meta object literal for the '<em><b>Objet de mail</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALEFASO_MAILAKA__OBJET_DE_MAIL = eINSTANCE.getAlefasoMailaka_Objet_de_mail();

    /**
     * The meta object literal for the '<em><b>Recipients</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALEFASO_MAILAKA__RECIPIENTS = eINSTANCE.getAlefasoMailaka_Recipients();

    /**
     * The meta object literal for the '<em><b>Sender</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALEFASO_MAILAKA__SENDER = eINSTANCE.getAlefasoMailaka_Sender();

    /**
     * The meta object literal for the '<em><b>Password</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALEFASO_MAILAKA__PASSWORD = eINSTANCE.getAlefasoMailaka_Password();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.mail.impl.EmailRecipientImpl <em>Email Recipient</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.mail.impl.EmailRecipientImpl
     * @see org.xtext.example.mydsl.mail.impl.MailPackageImpl#getEmailRecipient()
     * @generated
     */
    EClass EMAIL_RECIPIENT = eINSTANCE.getEmailRecipient();

    /**
     * The meta object literal for the '<em><b>Email</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EMAIL_RECIPIENT__EMAIL = eINSTANCE.getEmailRecipient_Email();

  }

} //MailPackage
