/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MailStandaloneSetup extends MailStandaloneSetupGenerated {

	public static void doSetup() {
		new MailStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
