/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.mail.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.mail.AlefasoMailaka;
import org.xtext.example.mydsl.mail.EmailRecipient;
import org.xtext.example.mydsl.mail.MailPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Alefaso Mailaka</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.mail.impl.AlefasoMailakaImpl#getMessage <em>Message</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mail.impl.AlefasoMailakaImpl#getObjet_de_mail <em>Objet de mail</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mail.impl.AlefasoMailakaImpl#getRecipients <em>Recipients</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mail.impl.AlefasoMailakaImpl#getSender <em>Sender</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.mail.impl.AlefasoMailakaImpl#getPassword <em>Password</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AlefasoMailakaImpl extends ModelImpl implements AlefasoMailaka
{
  /**
   * The default value of the '{@link #getMessage() <em>Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMessage()
   * @generated
   * @ordered
   */
  protected static final String MESSAGE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMessage() <em>Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMessage()
   * @generated
   * @ordered
   */
  protected String message = MESSAGE_EDEFAULT;

  /**
   * The default value of the '{@link #getObjet_de_mail() <em>Objet de mail</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjet_de_mail()
   * @generated
   * @ordered
   */
  protected static final String OBJET_DE_MAIL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getObjet_de_mail() <em>Objet de mail</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjet_de_mail()
   * @generated
   * @ordered
   */
  protected String objet_de_mail = OBJET_DE_MAIL_EDEFAULT;

  /**
   * The cached value of the '{@link #getRecipients() <em>Recipients</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRecipients()
   * @generated
   * @ordered
   */
  protected EList<EmailRecipient> recipients;

  /**
   * The default value of the '{@link #getSender() <em>Sender</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSender()
   * @generated
   * @ordered
   */
  protected static final String SENDER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSender() <em>Sender</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSender()
   * @generated
   * @ordered
   */
  protected String sender = SENDER_EDEFAULT;

  /**
   * The default value of the '{@link #getPassword() <em>Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPassword()
   * @generated
   * @ordered
   */
  protected static final String PASSWORD_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPassword() <em>Password</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPassword()
   * @generated
   * @ordered
   */
  protected String password = PASSWORD_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AlefasoMailakaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MailPackage.Literals.ALEFASO_MAILAKA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getMessage()
  {
    return message;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMessage(String newMessage)
  {
    String oldMessage = message;
    message = newMessage;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MailPackage.ALEFASO_MAILAKA__MESSAGE, oldMessage, message));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getObjet_de_mail()
  {
    return objet_de_mail;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setObjet_de_mail(String newObjet_de_mail)
  {
    String oldObjet_de_mail = objet_de_mail;
    objet_de_mail = newObjet_de_mail;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MailPackage.ALEFASO_MAILAKA__OBJET_DE_MAIL, oldObjet_de_mail, objet_de_mail));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EmailRecipient> getRecipients()
  {
    if (recipients == null)
    {
      recipients = new EObjectContainmentEList<EmailRecipient>(EmailRecipient.class, this, MailPackage.ALEFASO_MAILAKA__RECIPIENTS);
    }
    return recipients;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSender()
  {
    return sender;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSender(String newSender)
  {
    String oldSender = sender;
    sender = newSender;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MailPackage.ALEFASO_MAILAKA__SENDER, oldSender, sender));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPassword()
  {
    return password;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPassword(String newPassword)
  {
    String oldPassword = password;
    password = newPassword;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MailPackage.ALEFASO_MAILAKA__PASSWORD, oldPassword, password));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MailPackage.ALEFASO_MAILAKA__RECIPIENTS:
        return ((InternalEList<?>)getRecipients()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MailPackage.ALEFASO_MAILAKA__MESSAGE:
        return getMessage();
      case MailPackage.ALEFASO_MAILAKA__OBJET_DE_MAIL:
        return getObjet_de_mail();
      case MailPackage.ALEFASO_MAILAKA__RECIPIENTS:
        return getRecipients();
      case MailPackage.ALEFASO_MAILAKA__SENDER:
        return getSender();
      case MailPackage.ALEFASO_MAILAKA__PASSWORD:
        return getPassword();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MailPackage.ALEFASO_MAILAKA__MESSAGE:
        setMessage((String)newValue);
        return;
      case MailPackage.ALEFASO_MAILAKA__OBJET_DE_MAIL:
        setObjet_de_mail((String)newValue);
        return;
      case MailPackage.ALEFASO_MAILAKA__RECIPIENTS:
        getRecipients().clear();
        getRecipients().addAll((Collection<? extends EmailRecipient>)newValue);
        return;
      case MailPackage.ALEFASO_MAILAKA__SENDER:
        setSender((String)newValue);
        return;
      case MailPackage.ALEFASO_MAILAKA__PASSWORD:
        setPassword((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MailPackage.ALEFASO_MAILAKA__MESSAGE:
        setMessage(MESSAGE_EDEFAULT);
        return;
      case MailPackage.ALEFASO_MAILAKA__OBJET_DE_MAIL:
        setObjet_de_mail(OBJET_DE_MAIL_EDEFAULT);
        return;
      case MailPackage.ALEFASO_MAILAKA__RECIPIENTS:
        getRecipients().clear();
        return;
      case MailPackage.ALEFASO_MAILAKA__SENDER:
        setSender(SENDER_EDEFAULT);
        return;
      case MailPackage.ALEFASO_MAILAKA__PASSWORD:
        setPassword(PASSWORD_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MailPackage.ALEFASO_MAILAKA__MESSAGE:
        return MESSAGE_EDEFAULT == null ? message != null : !MESSAGE_EDEFAULT.equals(message);
      case MailPackage.ALEFASO_MAILAKA__OBJET_DE_MAIL:
        return OBJET_DE_MAIL_EDEFAULT == null ? objet_de_mail != null : !OBJET_DE_MAIL_EDEFAULT.equals(objet_de_mail);
      case MailPackage.ALEFASO_MAILAKA__RECIPIENTS:
        return recipients != null && !recipients.isEmpty();
      case MailPackage.ALEFASO_MAILAKA__SENDER:
        return SENDER_EDEFAULT == null ? sender != null : !SENDER_EDEFAULT.equals(sender);
      case MailPackage.ALEFASO_MAILAKA__PASSWORD:
        return PASSWORD_EDEFAULT == null ? password != null : !PASSWORD_EDEFAULT.equals(password);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (message: ");
    result.append(message);
    result.append(", objet_de_mail: ");
    result.append(objet_de_mail);
    result.append(", sender: ");
    result.append(sender);
    result.append(", password: ");
    result.append(password);
    result.append(')');
    return result.toString();
  }

} //AlefasoMailakaImpl
