/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.mail.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.mydsl.mail.AlefasoMailaka;
import org.xtext.example.mydsl.mail.EmailRecipient;
import org.xtext.example.mydsl.mail.MailFactory;
import org.xtext.example.mydsl.mail.MailPackage;
import org.xtext.example.mydsl.mail.Model;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MailPackageImpl extends EPackageImpl implements MailPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass alefasoMailakaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass emailRecipientEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.mydsl.mail.MailPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private MailPackageImpl()
  {
    super(eNS_URI, MailFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link MailPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static MailPackage init()
  {
    if (isInited) return (MailPackage)EPackage.Registry.INSTANCE.getEPackage(MailPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredMailPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    MailPackageImpl theMailPackage = registeredMailPackage instanceof MailPackageImpl ? (MailPackageImpl)registeredMailPackage : new MailPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theMailPackage.createPackageContents();

    // Initialize created meta-data
    theMailPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theMailPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(MailPackage.eNS_URI, theMailPackage);
    return theMailPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAlefasoMailaka()
  {
    return alefasoMailakaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlefasoMailaka_Message()
  {
    return (EAttribute)alefasoMailakaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlefasoMailaka_Objet_de_mail()
  {
    return (EAttribute)alefasoMailakaEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAlefasoMailaka_Recipients()
  {
    return (EReference)alefasoMailakaEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlefasoMailaka_Sender()
  {
    return (EAttribute)alefasoMailakaEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAlefasoMailaka_Password()
  {
    return (EAttribute)alefasoMailakaEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEmailRecipient()
  {
    return emailRecipientEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEmailRecipient_Email()
  {
    return (EAttribute)emailRecipientEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MailFactory getMailFactory()
  {
    return (MailFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);

    alefasoMailakaEClass = createEClass(ALEFASO_MAILAKA);
    createEAttribute(alefasoMailakaEClass, ALEFASO_MAILAKA__MESSAGE);
    createEAttribute(alefasoMailakaEClass, ALEFASO_MAILAKA__OBJET_DE_MAIL);
    createEReference(alefasoMailakaEClass, ALEFASO_MAILAKA__RECIPIENTS);
    createEAttribute(alefasoMailakaEClass, ALEFASO_MAILAKA__SENDER);
    createEAttribute(alefasoMailakaEClass, ALEFASO_MAILAKA__PASSWORD);

    emailRecipientEClass = createEClass(EMAIL_RECIPIENT);
    createEAttribute(emailRecipientEClass, EMAIL_RECIPIENT__EMAIL);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    alefasoMailakaEClass.getESuperTypes().add(this.getModel());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(alefasoMailakaEClass, AlefasoMailaka.class, "AlefasoMailaka", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAlefasoMailaka_Message(), ecorePackage.getEString(), "message", null, 0, 1, AlefasoMailaka.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlefasoMailaka_Objet_de_mail(), ecorePackage.getEString(), "objet_de_mail", null, 0, 1, AlefasoMailaka.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAlefasoMailaka_Recipients(), this.getEmailRecipient(), null, "recipients", null, 0, -1, AlefasoMailaka.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlefasoMailaka_Sender(), ecorePackage.getEString(), "sender", null, 0, 1, AlefasoMailaka.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAlefasoMailaka_Password(), ecorePackage.getEString(), "password", null, 0, 1, AlefasoMailaka.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(emailRecipientEClass, EmailRecipient.class, "EmailRecipient", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEmailRecipient_Email(), ecorePackage.getEString(), "email", null, 0, 1, EmailRecipient.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //MailPackageImpl
