/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.mail.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.mydsl.mail.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MailFactoryImpl extends EFactoryImpl implements MailFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static MailFactory init()
  {
    try
    {
      MailFactory theMailFactory = (MailFactory)EPackage.Registry.INSTANCE.getEFactory(MailPackage.eNS_URI);
      if (theMailFactory != null)
      {
        return theMailFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new MailFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MailFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case MailPackage.MODEL: return createModel();
      case MailPackage.ALEFASO_MAILAKA: return createAlefasoMailaka();
      case MailPackage.EMAIL_RECIPIENT: return createEmailRecipient();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AlefasoMailaka createAlefasoMailaka()
  {
    AlefasoMailakaImpl alefasoMailaka = new AlefasoMailakaImpl();
    return alefasoMailaka;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EmailRecipient createEmailRecipient()
  {
    EmailRecipientImpl emailRecipient = new EmailRecipientImpl();
    return emailRecipient;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MailPackage getMailPackage()
  {
    return (MailPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static MailPackage getPackage()
  {
    return MailPackage.eINSTANCE;
  }

} //MailFactoryImpl
